server:
  error:
    include-message: always
    include-binding-errors: always
  port: 2020


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: amil.xudaverdiyev30@gmail.com
    password: tvfwbmexlzwcfsou
    properties:
      mail:
        smtp:
            ssl:
                trust: "*"
            auth: true
            starttls.enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
  datasource:
   url: jdbc:postgresql://localhost:5432/online_food_commerce_ms
   username: postgres
   password: amil4477
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
    default-schema: public
    enabled: true
    database-change-log-table: onlinefoodcommerce_DBLOG
    database-change-log-lock-table: onlinefoodcommerce_DBLOCK
  quartz:
    scheduler-name:
      cron: '* * * * * *'
jwt:
  header: Authorization
  prefix: Bearer
  expiration: 3600000
  secretKey: 65hgfhDFSF!@!@33wdq3r3tsdGsf22VXv343&3l071&65hgfhDFSF!@!@33wdq3r3tsdGsf22VXv343&3l071&
shedLock:
  shedTableName: food_schedule
  checkTime: 0 00 13 * * *